apiVersion: v1
kind: Service
metadata:
  name: lingowords-lb
spec:
  selector:
    app: lingowords-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingowords-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lingowords-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: lingowords-service
    spec:
      containers:
        - name: lingowords-service
          image: ${DOCKER_USERNAME}/lingowords:$SEMAPHORE_WORKFLOW_ID
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: "production"
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /words
              port: 8080