# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
      branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
      
    - uses: actions/cache@v1
      with: 
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Build using Maven
      run: mvn clean package
    
    - name: Save Result
      uses: actions/upload-artifact@v1
      with:
        name: build-result
        path: target
        
  package-jar:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Load result
        uses: actions/download-artifact@v1
        with:
          name: build-result
          path: target
          
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with: 
          java-version: 14
      
      - name: Publish jar to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          DISTRIBUTION_ID: github
          DISTRIBUTION_NAME: lingowords
          DISTRIBUTION_URL: https://maven.pkg.github.com/${{ github.repository }}
  
  deploy-heroku:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "lingosource"
          heroku_email: "niels_daalhuisen@hotmail.com"
